services:
  api:
    build:
      context: docker_config/web/
    container_name: matsu-api
    env_file:
      - ./src/www/.env.local
    ports:
      - 18080:80
    working_dir: /var/www
    command:
      - /bin/sh
      - -c
      - |
        rm -f bootstrap/cache/config.php
        exec apache2-foreground
    volumes:
      - ./src/www/:/var/www
      - api_framework_data:/var/www/storage/framework
      - api_vendor_data:/var/www/vendor
    depends_on:
      - api-db
  api-db:
    build:
      context: docker_config/db/
    container_name: matsu-api-db
    volumes:
      # ここにdbデータがある（バックアップを最後にvolumeする）
      - api_db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=matsu
      - MYSQL_HOST=localhost
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_user_pass
      - MYSQL_ROOT_PASSWORD=test_root_pass
      - TZ=Asia/Tokyo
    ports:
      - 13306:3306
volumes:
  api_db_data:
    name: matsu-api-db-data
  api_framework_data:
    name: matsu-api-framework-data
  api_vendor_data:
    name: matsu-api-vendor-data
